### PR TITLE
replace PbsParameters with SmoothLightingParameters

### PR DESCRIPTION
**Pull request by felixzsh**
just clone it and try to compile but there was this error, so i checkout the expected type and fix this, now it runs in release mode

### CODE REVIEW

**Comment by Adamkob12** [comment]
Thanks!

**Comment by ghost** [comment]
Hmm, this does not compile for me.

```console
error[E0422]: cannot find struct, variant or union type `SmoothLightingParameters` in this scope
   --> src/chunk/chunk_queue.rs:137:34
    |
137 | ...                   Some(SmoothLightingParameters {
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0422`.
error: could not compile `minecraft_bevy` (bin "minecraft_bevy") due to previous error
```

**Comment by Adamkob12** [comment]
Hmmm. Are the dependencies up to date? Could you try 'cargo update'?

**Comment by ghost** [comment]
`cargo update` fixed it, thanks!

**Pull request merged**
